
#ifndef HISSTOOLS_LIBRARY_NAMESPACE_HPP
#define HISSTOOLS_LIBRARY_NAMESPACE_HPP

#ifndef HISSTOOLS_LIBRARY_NAMESPACE_SYMBOL
#define HISSTOOLS_LIBRARY_NAMESPACE_SYMBOL htl
#endif

#define HISSTOOLS_LIBRARY_NAMESPACE_START() namespace HISSTOOLS_LIBRARY_NAMESPACE_SYMBOL {
#define HISSTOOLS_LIBRARY_NAMESPACE_END() }

#endif /* HISSTOOLS_LIBRARY_NAMESPACE_HPP */
