
#ifndef HISSTOOLS_NAMESPACE_HPP
#define HISSTOOLS_NAMESPACE_HPP

#define HISSTOOLS_NAMESPACE_SYMBOL htl

#define HISSTOOLS_NAMESPACE_START() namespace HISSTOOLS_NAMESPACE_SYMBOL {
#define HISSTOOLS_NAMESPACE_END() }

#endif /* HISSTOOLS_NAMESPACE_HPP */